// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaPF2Kg69fZyda9DdqI4rmkM0hzwbqGOM',
    appId: '1:792313855472:web:cf060d97e37075cbdcb135',
    messagingSenderId: '792313855472',
    projectId: 'tpflutter-6fba9',
    authDomain: 'tpflutter-6fba9.firebaseapp.com',
    storageBucket: 'tpflutter-6fba9.appspot.com',
    measurementId: 'G-J88MEXBH41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBD40uHhFEOOC5cm6-a5m8vqNb4vtPP4',
    appId: '1:792313855472:android:f5e323f87ef78ca2dcb135',
    messagingSenderId: '792313855472',
    projectId: 'tpflutter-6fba9',
    storageBucket: 'tpflutter-6fba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzGalNRCs5udGhAUfivopoD1WuZv4fr4',
    appId: '1:792313855472:ios:63b627407f95c14fdcb135',
    messagingSenderId: '792313855472',
    projectId: 'tpflutter-6fba9',
    storageBucket: 'tpflutter-6fba9.appspot.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtzGalNRCs5udGhAUfivopoD1WuZv4fr4',
    appId: '1:792313855472:ios:63b627407f95c14fdcb135',
    messagingSenderId: '792313855472',
    projectId: 'tpflutter-6fba9',
    storageBucket: 'tpflutter-6fba9.appspot.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaPF2Kg69fZyda9DdqI4rmkM0hzwbqGOM',
    appId: '1:792313855472:web:2be066dc9b9eb34ddcb135',
    messagingSenderId: '792313855472',
    projectId: 'tpflutter-6fba9',
    authDomain: 'tpflutter-6fba9.firebaseapp.com',
    storageBucket: 'tpflutter-6fba9.appspot.com',
    measurementId: 'G-0CYTHX1HM7',
  );
}
